version: '3.8'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tmdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TMDB_API_KEY=your_api_key
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tmdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6
    ports:
      - '6379:6379'
volumes:
  postgres_data:
